name: Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_DEPLOY_KEY }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker buildx build -t "${DOCKER_USER}/dockerize:latest" \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --push .
  